version: '3.7'

services:
  dynamodb-local:
    container_name: dynamodb-local
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin
    ports:
      - 8001:8001
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
      AWS_ACCESS_KEY_ID: abcdefghijklmnop
      AWS_SECRET_ACCESS_KEY: abcdefghiklmnop
      AWS_REGION: ap-south-1
  dynamodb-bootstrap:
    container_name: dynamodb-bootstrap
    image: rajalokan/dynamodb-bootstrap
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
      AWS_ACCESS_KEY_ID: abcdefghijklmnop
      AWS_SECRET_ACCESS_KEY: abcdefghiklmnop
      AWS_REGION: ap-south-1
    volumes:
    - ./data:/code/data:ro

